### 
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nome_completo": "lucas ventura",
  "email": "lucas@email.com",
  "senha": "12345678"
}

###
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nome_completo": "lucas",
  "email": "lucas-email",
  "senha": "123"
}